---
- name: ensure glance packages and dependencies are installed
  apt: 
    pkg: "{{ item }}"
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - mysql-client
    - python-glanceclient
    - python-mysqldb
    - glance

- name: ensure glance is started and enabled
  service: 
    name: "{{ item }}"
    state: started 
    enabled: yes
  with_items:
    - glance-registry
    - glance-api

- name: ensure glance is properly shut down for dockerized deployments
  service:
    name: "{{ item }}"
    state: stopped
    enabled: yes
  with_items:
    - glance-registry
    - glance-api
  when: glance_dockerize_context is defined

- name: ensure supervisor is installed for dockerized deployments 
  apt: 
    pkg: "{{ item }}"
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - supervisor
  when: glance_dockerize_context is defined

- name: update supervisor configuration from template for dockerized deployments
  template:
    src: etc/supervisor/conf.d/supervisord.conf
    dest: /etc/supervisor/conf.d/supervisord.conf
    owner: root
    group: root
    mode: 0644
  when: glance_dockerize_context is defined


