---
- name: ensure openstack cinder requirements packages are installed
  action: "{{ openstack_cinder_package_info.pkg_mgr }}"
  args: openstack_cinder_package_info.args
  with_items: openstack_cinder_package_info.pre_pkgs
  when: openstack_cinder_package_info.pre_pkgs|length > 0

- name: ensure openstack repository is enabled
  action: "{{ openstack_cinder_repo_info.pkg_repo }}"
  args: openstack_cinder_repo_info.args
  with_items: openstack_cinder_repo_info.repos
  when: openstack_cinder_repo_info.repos|length > 0

- name: ensure openstack cinder packages are installed
  action: "{{ openstack_cinder_package_info.pkg_mgr }}"
  args: openstack_cinder_package_info.args
  with_items: openstack_cinder_package_info.pkgs
  when: openstack_cinder_package_info.pkgs|length > 0

- name: ensure cinder services are started and enabled
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: openstack_cinder_services
  when: openstack_cinder_services|length > 0
