---
- name: ensure glance packages and dependencies are installed
  apt: 
    pkg: "{{ item }}"
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - mysql-client
    - python-glanceclient
    - python-mysqldb
    - glance

- name: ensure glance is started and enabled
  service: 
    name: "{{ item }}"
    state: started 
    enabled: yes
  with_items:
    - glance-registry
    - glance-api
