---
- name: create glance user in keystone
  keystone_user:
    endpoint: "{{ openstack_identity_admin_url }}"
    token: "{{ openstack_identity_admin_token }}"
    tenant: service
    user: glance
    password: "{{ openstack_identity_glance_password }}"

- name: add glance user to the service tenant with the admin role
  keystone_user:
    endpoint: "{{ openstack_identity_admin_url }}"
    token: "{{ openstack_identity_admin_token }}"
    tenant: service
    user: glance
    role: admin

- name: add glance endpoint
  keystone_service:
    endpoint: "{{ openstack_identity_admin_url }}"
    token: "{{ openstack_identity_admin_token }}"
    region: "{{ openstack_identity_region }}"
    name: glance
    type: image
    description: "Image Service"
    public_url: "{{ openstack_image_public_url }}"
    internal_url: "{{ openstack_image_internal_url }}"
    admin_url: "{{ openstack_image_admin_url }}"
