---
- name: ensure cinder user has been created in keystone
  environment:
    http_proxy: ''
    HTTP_PROXY: ''
  keystone_user:
    endpoint: "{{ openstack_identity_admin_url }}"
    token: "{{ openstack_identity_admin_token }}"
    tenant: service
    user: cinder
    password: "{{ openstack_identity_cinder_password }}"

- name: ensure cinder user has been added to service tenant with admin role
  environment:
    http_proxy: ''
    HTTP_PROXY: ''
  keystone_user:
    endpoint: "{{ openstack_identity_admin_url }}"
    token: "{{ openstack_identity_admin_token }}"
    tenant: service
    user: cinder
    role: admin

- name: ensure cinder endpoint information has been added to keystone
  environment:
    http_proxy: ''
    HTTP_PROXY: ''
  keystone_service:
    endpoint: "{{ openstack_identity_admin_url }}"
    token: "{{ openstack_identity_admin_token }}"
    region: "{{ openstack_identity_region }}"
    name: cinder
    type: volume
    description: "Block Storage Service"
    public_url: "{{ openstack_volume_public_url }}"
    internal_url: "{{ openstack_volume_internal_url }}"
    admin_url: "{{ openstack_volume_admin_url }}"

- name: ensure cinderv2 endpoint information has been added to keystone
  environment:
    http_proxy: ''
    HTTP_PROXY: ''
  keystone_service:
    endpoint: "{{ openstack_identity_admin_url }}"
    token: "{{ openstack_identity_admin_token }}"
    region: "{{ openstack_identity_region }}"
    name: cinderv2
    type: volumev2
    description: "Block Storage v2 Service"
    public_url: "{{ openstack_volumev2_public_url }}"
    internal_url: "{{ openstack_volumev2_internal_url }}"
    admin_url: "{{ openstack_volumev2_admin_url }}"

