---
- name: ensure glance user has been created in keystone
  environment:
    http_proxy: ''
    HTTP_PROXY: ''
  keystone_user:
    endpoint: "{{ openstack_identity_admin_url }}"
    token: "{{ openstack_identity_admin_token }}"
    tenant: service
    user: glance
    password: "{{ openstack_identity_glance_password }}"

- name: ensure glance user has been added to service tenant with admin role
  environment:
    http_proxy: ''
    HTTP_PROXY: ''
  keystone_user:
    endpoint: "{{ openstack_identity_admin_url }}"
    token: "{{ openstack_identity_admin_token }}"
    tenant: service
    user: glance
    role: admin

- name: ensure glance endpoint information has been added to keystone
  environment:
    http_proxy: ''
    HTTP_PROXY: ''
  keystone_service:
    endpoint: "{{ openstack_identity_admin_url }}"
    token: "{{ openstack_identity_admin_token }}"
    region: "{{ openstack_identity_region }}"
    name: glance
    type: image
    description: "Image Service"
    public_url: "{{ openstack_image_public_url }}"
    internal_url: "{{ openstack_image_internal_url }}"
    admin_url: "{{ openstack_image_admin_url }}"
