---
- include: mysql.yml

- include: docker.yml
  when: glance_dockerized_deployment

- include: install.yml
  when: not glance_dockerized_deployment 

- include: configure.yml
  when: not glance_dockerized_deployment 

- include: keystone.yml
