---
# FIXME: for security we assume root login requires direct login access to mysql
# node, needs delegate_to for non-centralized deployments.

- name: ensure glance database is present
  mysql_db:
    login_host: 127.0.0.1
    login_port: "{{ openstack_mysql_port }}"
    login_user: root
    login_password: "{{ openstack_mysql_root_password }}"
    name: glance
  register: create_glance_db

- name: ensure glance database user is present
  mysql_user:
    login_host: 127.0.0.1
    login_port: "{{ openstack_mysql_port }}"
    login_user: root
    login_password: "{{ openstack_mysql_root_password }}"
    name: glance
    host: "{{ item }}"
    password: "{{ openstack_mysql_glance_password }}"
    priv: glance.*:ALL
  with_items:
    - localhost
    - "%"
