---
- name: ensure glance is properly configured
  ini_file:
    dest: /etc/glance/glance-{{ item[0] }}.conf
    owner: glance
    group: glance
    mode: 0600
    section: "{{ item[1].section }}"
    option: "{{ item[1].option }}"
    value: "{{ item[1].value }}"
  with_nested:
    - [ 'api', 'registry' ]
    - 
      - { section: DEFAULT, option: verbose, value: "{{ glance_log_verbose }}" }
      - { section: DEFAULT, option: debug, value: "{{ glance_log_debug }}" }
      - { section: DEFAULT, option: log_dir, value: "{{ glance_log_dir }}" }
      - { section: database, option: connection,
          value: "mysql://glance:{{ glance_mysql_glance_password }}@{{ 
                    glance_mysql_host }}:{{ glance_mysql_port }}/glance" }
      - { section: database, option: db_enforce_mysql_charset,
          value: False }
      - { section: keystone_authtoken, option: auth_uri, 
          value: "{{ glance_identity_internal_url }}" }
      - { section: keystone_authtoken, option: auth_host, 
          value: "{{ glance_identity_endpoint_host }}" }
      - { section: keystone_authtoken, option: auth_port, value: 35357 }
      - { section: keystone_authtoken, option: auth_protocol, value: http }
      - { section: keystone_authtoken, option: admin_tenant_name, 
          value: service }
      - { section: keystone_authtoken, option: admin_user, value: glance }
      - { section: keystone_authtoken, option: admin_password, 
          value: "{{ glance_identity_glance_password }}" }
      - { section: paste_deploy, option: flavor, value: keystone }
  register: modify_glance_ini

- name: ensure glance sqlite is deleted
  file:
    dest: /var/lib/glance/glance.sqlite
    state: absent

- name: ensure glance database has been populated with required tables
  sudo_user: glance
  command: /usr/bin/glance-manage db_sync
  when: glance_dockerize_context is defined or
        create_glance_db|changed
  failed_when: false

- name: update glance workaround script from template
  template:
    src: var/lib/glance/glance-mysql-utf8-workaround.sh
    dest: /var/lib/glance/glance-mysql-utf8-workaround.sh
    owner: glance
    group: glance
    mode: 0700 

- name: run glance database workaround script
  sudo_user: glance
  command: /var/lib/glance/glance-mysql-utf8-workaround.sh
  when: glance_dockerize_context is defined or
        create_glance_db|changed

- name: restart glance
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - glance-registry
    - glance-api
  when: modify_glance_ini|changed and
        glance_dockerize_context is not defined
